"""
data/generators/quality_report.py
Generate a data quality report for all synthetic datasets.

Checks:
  1. Row counts
  2. Missing values
  3. Value range validation against physics bounds
  4. Class balance (for dyno cards)
  5. SOR trend across cycles (must be increasing)
  6. Viscosity vs temperature correlation (must be negative)
  7. Overall provenance consistency
"""
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime


def _range_check(df: pd.DataFrame, col: str, lo: float, hi: float) -> dict:
    if col not in df.columns:
        return {"col": col, "status": "MISSING", "violations": 0}
    vals = pd.to_numeric(df[col], errors="coerce").dropna()
    bad = ((vals < lo) | (vals > hi)).sum()
    return {
        "column": col,
        "expected_range": f"[{lo}, {hi}]",
        "min_found": round(float(vals.min()), 4) if len(vals) else None,
        "max_found": round(float(vals.max()), 4) if len(vals) else None,
        "violations": int(bad),
        "status": "OK" if bad == 0 else "WARN",
    }


def generate_quality_report(output_dir: Path) -> dict:
    """
    Generate a comprehensive data quality report for all datasets in output_dir.

    Returns a dict that is also written to data/synthetic/quality_report.json.
    """
    output_dir = Path(output_dir)
    report = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "provenance_disclaimer": (
            "All datasets are SYNTHETIC_HISTORICAL — generated by the physics simulator. "
            "Calibrated to published literature. NOT validated on real Baghewala data."
        ),
        "datasets": {},
    }

    # ── 1. Well Completion ────────────────────────────────────────────────
    p = output_dir / "well_completion.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        checks = [
            _range_check(df, "initial_reservoir_temp_c", 44.0, 50.0),  # FIELD_FACT: 46-48°C
            _range_check(df, "api_gravity", 16.0, 21.0),               # FIELD_FACT: 17-19°API
            _range_check(df, "porosity_fraction", 0.10, 0.35),
            _range_check(df, "permeability_md", 100.0, 1200.0),
        ]
        report["datasets"]["well_completion"] = {
            "rows": len(df),
            "columns": len(df.columns),
            "missing_values": int(df.isnull().sum().sum()),
            "range_checks": checks,
            "status": "OK" if all(c["status"] == "OK" for c in checks) else "WARN",
        }

    # ── 2. CSS Cycle Records ──────────────────────────────────────────────
    p = output_dir / "css_cycle_records.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        checks = [
            _range_check(df, "steam_volume_cwe_m3", 100.0, 1500.0),
            _range_check(df, "injection_pressure_kpa", 1500.0, 8000.0),
            _range_check(df, "steam_quality_fraction", 0.50, 1.0),
            _range_check(df, "soak_days", 3.0, 60.0),
            _range_check(df, "peak_reservoir_temp_c", 44.0, 220.0),  # can be near initial T for small steam
            _range_check(df, "cycle_sor", 0.1, 100.0),               # high SOR valid for late cycles
        ]

        # Check SOR trend: cycle N+1 should have >= SOR than cycle N (on average)
        sor_trend_ok = True
        if "cycle_number" in df.columns and "cycle_sor" in df.columns:
            avg_sor_by_cycle = df.groupby("cycle_number")["cycle_sor"].mean()
            if len(avg_sor_by_cycle) >= 2:
                sor_diffs = avg_sor_by_cycle.diff().dropna()
                sor_trend_ok = bool((sor_diffs >= 0).mean() >= 0.6)  # ≥60% non-decreasing

        report["datasets"]["css_cycle_records"] = {
            "rows": len(df),
            "columns": len(df.columns),
            "missing_values": int(df.isnull().sum().sum()),
            "range_checks": checks,
            "sor_trend_increasing": sor_trend_ok,
            "n_wells": int(df["well_id"].nunique()),
            "n_cycles_per_well": round(len(df) / max(df["well_id"].nunique(), 1), 1),
            "status": "OK" if all(c["status"] == "OK" for c in checks) and sor_trend_ok else "WARN",
        }

    # ── 3. Production History ─────────────────────────────────────────────
    p = output_dir / "production_history.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        prod = df[df["phase"] == "production"]
        checks = [
            _range_check(prod, "oil_rate_m3d", 0.0, 100.0),
            _range_check(prod, "water_cut_fraction", 0.0, 1.0),
            _range_check(prod, "reservoir_temp_c", 40.0, 220.0),
            _range_check(prod, "sor", 0.0, 5000.0),  # SOR is unbounded early when cum_oil ~0
        ]

        # Check viscosity-temperature anti-correlation
        visc_temp_ok = True
        if "reservoir_temp_c" in prod.columns and "oil_rate_m3d" in prod.columns:
            # Higher temperature → higher oil rate (via lower viscosity/IPR)
            # Use rate vs temp as proxy
            temp_rate_corr = prod[["reservoir_temp_c", "oil_rate_m3d"]].corr().iloc[0, 1]
            visc_temp_ok = float(temp_rate_corr) > 0.0  # positive correlation expected

        report["datasets"]["production_history"] = {
            "rows": len(df),
            "columns": len(df.columns),
            "missing_values": int(df.isnull().sum().sum()),
            "range_checks": checks,
            "phase_distribution": df["phase"].value_counts().to_dict(),
            "production_rows": len(prod),
            "temp_rate_correlation": round(float(temp_rate_corr), 3) if "temp_rate_corr" in dir() else None,
            "temp_rate_positive": visc_temp_ok,
            "status": "OK" if all(c["status"] == "OK" for c in checks) else "WARN",
        }

    # ── 4. SRP Operating Data ─────────────────────────────────────────────
    p = output_dir / "srp_operating_data.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        checks = [
            _range_check(df, "spm", 1.0, 15.0),
            _range_check(df, "stroke_length_m", 0.5, 5.0),
            _range_check(df, "vfd_frequency_hz", 15.0, 65.0),
            _range_check(df, "pump_fillage_fraction", 0.0, 1.10),   # small noise can push above 1.0
            _range_check(df, "pump_efficiency_fraction", 0.0, 1.0),
            _range_check(df, "kwh_per_bbl", 0.5, 1000.0),           # high at low flow rates
            _range_check(df, "rod_float_risk_ratio", 0.0, 20.0),
        ]
        report["datasets"]["srp_operating_data"] = {
            "rows": len(df),
            "columns": len(df.columns),
            "missing_values": int(df.isnull().sum().sum()),
            "range_checks": checks,
            "float_risk_events": int((df["rod_float_risk_ratio"] >= 1.0).sum()),
            "float_risk_pct": round(float((df["rod_float_risk_ratio"] >= 1.0).mean() * 100), 2),
            "status": "OK" if all(c["status"] == "OK" for c in checks) else "WARN",
        }

    # ── 5. Dynamometer Cards ──────────────────────────────────────────────
    p = output_dir / "dyno_cards_labeled.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        class_dist = df["fault_label"].value_counts(normalize=True).round(3).to_dict()
        checks = [
            _range_check(df, "fillage_fraction", 0.0, 1.0),
            _range_check(df, "pump_efficiency_fraction", 0.0, 1.0),
            _range_check(df, "rod_float_risk_ratio", 0.0, 20.0),
        ]
        report["datasets"]["dyno_cards_labeled"] = {
            "rows": len(df),
            "columns": len(df.columns),
            "missing_values": int(df.isnull().sum().sum()),
            "class_distribution": class_dist,
            "range_checks": checks,
            "n_classes": int(df["fault_label"].nunique()),
            "status": "OK" if all(c["status"] == "OK" for c in checks) else "WARN",
        }

    # ── 6. Rod Failure History ────────────────────────────────────────────
    p = output_dir / "rod_failure_history.parquet"
    if p.exists():
        df = pd.read_parquet(p)
        if len(df) > 0:
            checks = [
                _range_check(df, "risk_score_at_failure", 0.0, 100.0),
                _range_check(df, "goodman_ratio_at_failure", 0.0, 5.0),
                _range_check(df, "rod_float_ratio_at_failure", 0.0, 20.0),
            ]
            report["datasets"]["rod_failure_history"] = {
                "rows": len(df),
                "columns": len(df.columns),
                "missing_values": int(df.isnull().sum().sum()),
                "failure_type_distribution": df["failure_type"].value_counts().to_dict(),
                "range_checks": checks,
                "status": "OK" if all(c["status"] == "OK" for c in checks) else "WARN",
            }
        else:
            report["datasets"]["rod_failure_history"] = {
                "rows": 0,
                "status": "WARN",
                "note": "No failure events generated — may need more cycles or lower failure threshold."
            }

    # ── Summary ───────────────────────────────────────────────────────────
    dataset_statuses = [v.get("status", "UNKNOWN") for v in report["datasets"].values()]
    report["overall_status"] = "OK" if all(s == "OK" for s in dataset_statuses) else "WARN"
    report["total_rows"] = sum(
        v.get("rows", 0) for v in report["datasets"].values()
    )

    return report
