"""
data/generators/rod_failures.py
Generate synthetic rod failure and pump unsetting event history.

Dataset: SYNTHETIC_HISTORICAL
Failure events are generated by:
  1. Tracking the Goodman fatigue ratio throughout SRP operating history.
  2. Injecting failure events when the ratio exceeds threshold + random component.
  3. Failure probability increases with high viscosity (rod floating history),
     high SPM, and high cycle number (cumulative fatigue).

Reference:
  Shigley, J.E. (2011) Mechanical Engineering Design, 9th ed., McGraw-Hill, Ch. 6.
  API Spec 11B (2013) Sucker Rods.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import pandas as pd
import numpy as np
from simulator.config import (
    make_well_fleet, STEAM_TEMPERATURE_C,
    ROD_ENDURANCE_LIMIT_MPA, ROD_ULTIMATE_STRENGTH_MPA,
)
from simulator.reservoir.heated_zone import peak_temperature_c, reservoir_temperature_c
from simulator.wellbore.viscosity import viscosity_cp
from simulator.srp.wave_equation import simulate_stroke
from simulator.srp.rod_float import rod_float_risk_ratio


def _goodman_ratio(peak_kn, min_kn, rod_dia_m):
    """Goodman fatigue ratio for given load swing. >1.0 = unsafe."""
    A = np.pi / 4 * rod_dia_m ** 2
    F_max = peak_kn * 1000
    F_min = min_kn * 1000
    sigma_mean = (F_max + F_min) / (2 * max(A, 1e-9))
    sigma_alt = (F_max - F_min) / (2 * max(A, 1e-9))
    Se = ROD_ENDURANCE_LIMIT_MPA * 1e6
    Su = ROD_ULTIMATE_STRENGTH_MPA * 1e6
    return sigma_alt / Se + sigma_mean / Su


def generate_rod_failures(
    n_wells: int = 10,
    n_cycles: int = 8,
    seed: int = 42,
    start_date: str = "2019-01-01",
) -> pd.DataFrame:
    """
    Generate rod failure and pump unsetting event history.

    Returns
    -------
    pd.DataFrame  matching rod_failure_history.schema.json
    """
    from datetime import datetime, timedelta
    fleet = make_well_fleet(n_wells, seed)
    rng = np.random.default_rng(seed)
    records = []

    for w in fleet:
        w_start = datetime.fromisoformat(start_date) + timedelta(
            days=int(rng.integers(0, 30))
        )
        current_date = w_start
        inject_duration = 7.0
        cumulative_float_days = 0.0  # tracks cumulative rod floating exposure

        for cycle_n in range(1, n_cycles + 1):
            current_date += timedelta(days=int(inject_duration + w.soak_days))
            T_peak = peak_temperature_c(
                w.steam_volume_cwe_m3, w.steam_quality, w.pay_thickness_m,
                w.porosity, w.initial_temp_c, STEAM_TEMPERATURE_C,
                cycle_number=cycle_n,
            )
            from simulator.reservoir.ipr import (
                reservoir_pressure_decline, water_oil_ratio, vogel_oil_rate
            )
            from simulator.config import (
                FLOWING_BOTTOMHOLE_PRESSURE_KPA,
                PI_REFERENCE_M3_DAY_KPA, VISCOSITY_REFERENCE_CP,
            )
            Pr = w.reservoir_pressure_kpa
            t_prod = 0.0

            while t_prod < 200:
                T_res = reservoir_temperature_c(T_peak, w.initial_temp_c, t_prod)
                mu = viscosity_cp(T_res, w.api_gravity)
                Pr = reservoir_pressure_decline(Pr, 1.0)
                q_oil = vogel_oil_rate(Pr, FLOWING_BOTTOMHOLE_PRESSURE_KPA, mu,
                                       PI_REFERENCE_M3_DAY_KPA, VISCOSITY_REFERENCE_CP)
                wor = water_oil_ratio(t_prod, T_peak, w.initial_temp_c)

                dyno = simulate_stroke(
                    stroke_length_m=w.stroke_length_m,
                    spm=w.spm,
                    rod_length_m=w.rod_string_length_m,
                    rod_diameter_m=w.rod_diameter_m,
                    plunger_dia_m=w.pump_plunger_dia_m,
                    oil_viscosity_cp=mu,
                    reservoir_pressure_kpa=Pr,
                    oil_rate_m3d=max(q_oil, 0.001),
                    pump_depth_m=w.depth_m,
                )
                rf = rod_float_risk_ratio(
                    w.stroke_length_m, w.spm, w.rod_diameter_m,
                    w.rod_string_length_m, mu
                )
                gm = _goodman_ratio(dyno.peak_load_kn, dyno.min_load_kn, w.rod_diameter_m)
                if rf > 1.0:
                    cumulative_float_days += 1.0

                # Failure probability model (LITERATURE_ASSUMPTION):
                # P_fail(day) = base × (1 + 3×RF_excess + 2×GM_excess + 0.1×float_days)
                RF_excess = max(rf - 1.0, 0.0)
                GM_excess = max(gm - 0.80, 0.0)
                p_fail = 0.0005 * (1.0 + 3.0 * RF_excess + 2.0 * GM_excess
                                    + 0.01 * cumulative_float_days)
                p_fail = min(p_fail, 0.05)

                if rng.random() < p_fail:
                    fail_day = current_date + timedelta(days=int(t_prod))
                    # Failure type probabilistic: rod_break most common, then pump_unset
                    fail_weights = [0.45, 0.30, 0.15, 0.10]
                    fail_types = ["rod_break", "pump_unset", "rod_part", "tubing_wear"]
                    fail_type = str(rng.choice(fail_types, p=fail_weights))
                    depth = float(rng.uniform(
                        w.depth_m * 0.3, w.depth_m * 0.8
                    ))
                    records.append({
                        "well_id": w.well_id,
                        "failure_date": fail_day.strftime("%Y-%m-%d"),
                        "cycle_number": cycle_n,
                        "failure_type": fail_type,
                        "depth_m": round(depth, 1),
                        "t_production_days_at_failure": round(t_prod, 1),
                        "risk_score_at_failure": round(
                            min(RF_excess * 50 + GM_excess * 30 + cumulative_float_days * 0.5,
                                100.0), 1),
                        "goodman_ratio_at_failure": round(gm, 4),
                        "rod_float_ratio_at_failure": round(rf, 4),
                        "reservoir_temp_c": round(T_res, 2),
                        "oil_viscosity_cp": round(mu, 1),
                        "spm_at_failure": round(w.spm, 2),
                        "peak_load_kn_at_failure": round(dyno.peak_load_kn, 3),
                        "provenance": "SYNTHETIC_HISTORICAL",
                    })
                    # After failure, reset cumulative float counter (workover)
                    cumulative_float_days = 0.0

                t_prod += 1.0
                if wor >= w.production_cutoff_wor:
                    break

            current_date += timedelta(days=int(t_prod))
            current_date += timedelta(days=int(rng.integers(3, 10)))

    df = pd.DataFrame(records)
    if len(df) > 0:
        df["failure_date"] = pd.to_datetime(df["failure_date"])
        df = df.sort_values(["well_id", "failure_date"]).reset_index(drop=True)
    return df
