"""
simulator/surrogate/fast_surrogate.py
Fast vectorized surrogate of the full physics simulator.

Purpose: The joint optimizer calls the surrogate thousands of times.
The full wave-equation simulator is accurate but ~5ms per call.
This surrogate uses fitted polynomial/lookup approximations of the full
simulator over the operating envelope, enabling interactive what-if and
fast Optuna optimization.

Accuracy vs full simulator (documented in tests/test_surrogate.py):
  oil_rate_m3d     R² ≥ 0.97
  pump_efficiency  R² ≥ 0.95
  kwh_per_bbl      R² ≥ 0.95
  rod_float_risk   R² ≥ 0.98
  peak_load_kn     R² ≥ 0.96

The surrogate is NOT used for dyno card generation (needs wave equation)
or for final recommendation display (uses full simulator).

Architecture:
  Each output is modeled as a polynomial function of the key inputs,
  with coefficients fitted to a grid of full-simulator evaluations.
  The grid is generated by generate_surrogate_grid() and stored in
  models/artifacts/surrogate_coeffs.npz.
  If the file is absent, default analytic approximations are used.
"""

import numpy as np
from dataclasses import dataclass
from ..config import (
    FLOWING_BOTTOMHOLE_PRESSURE_KPA,
    VISCOSITY_REFERENCE_CP,
    PI_REFERENCE_M3_DAY_KPA,
    MOTOR_EFFICIENCY,
    DYNO_CARD_POINTS,
)
from ..wellbore.viscosity import viscosity_cp
from ..reservoir.ipr import vogel_oil_rate, productivity_index
from ..srp.rod_float import rod_float_risk_ratio, rod_float_risk_score_0_100
from ..reservoir.heated_zone import reservoir_temperature_c, peak_temperature_c


@dataclass
class SurrogateResult:
    """Output of one surrogate evaluation."""
    reservoir_temp_c: float
    oil_viscosity_cp: float
    oil_rate_m3d: float
    pump_fillage_fraction: float
    pump_efficiency_fraction: float
    motor_power_kw: float
    kwh_per_bbl: float
    peak_load_kn: float
    min_load_kn: float
    rod_float_risk: float
    rod_float_risk_score: float
    sor: float


def evaluate(
    # CSS state
    steam_volume_cwe_m3: float,
    steam_quality: float,
    t_production_days: float,
    cycle_number: int,
    T_initial_c: float,
    T_steam_c: float,
    pay_thickness_m: float,
    porosity: float,
    reservoir_pressure_kpa: float,
    # SRP config
    spm: float,
    stroke_length_m: float,
    rod_length_m: float,
    rod_diameter_m: float,
    plunger_dia_m: float,
    motor_efficiency: float = MOTOR_EFFICIENCY,
    # Well properties
    api: float = 18.0,
    # Prior cumulative oil for SOR
    cum_oil_m3: float = 1.0,
) -> SurrogateResult:
    """
    Fast surrogate evaluation: propagates inputs through the model chain.

    Chain (same as full simulator, but using analytic approximations):
      steam + soak → T_peak → T(t_prod) → μ(T) → PI(μ) → q_oil (Vogel)
      → SRP load, fillage, efficiency, power, kWh/bbl (API RP 11L approx)
      → rod float risk (Stokes/plunger demand)
      → SOR

    This is NOT a black-box ML model — it is a simplified physics chain.
    Its accuracy vs full simulator is documented in test_surrogate.py.

    Parameters are the same subset used by the joint optimizer.
    """
    # 1. Reservoir temperature at current production time
    T_peak = peak_temperature_c(
        steam_volume_cwe_m3, steam_quality, pay_thickness_m, porosity,
        T_initial_c, T_steam_c, cycle_number=cycle_number,
    )
    T_res = reservoir_temperature_c(T_peak, T_initial_c, t_production_days)

    # 2. Viscosity at current reservoir temperature
    mu = viscosity_cp(T_res, api)

    # 3. Oil production rate (Vogel IPR + viscosity-coupled PI)
    q_oil = vogel_oil_rate(
        reservoir_pressure_kpa, FLOWING_BOTTOMHOLE_PRESSURE_KPA,
        mu, PI_REFERENCE_M3_DAY_KPA, VISCOSITY_REFERENCE_CP,
    )

    # 4. SRP load — API RP 11L simplified approach [3]
    # Peak polished-rod load ≈ fluid load + rod weight in fluid + acceleration
    A_plunger = np.pi / 4.0 * plunger_dia_m**2        # [m²]
    rho_fluid = 900.0
    g = 9.81
    F_fluid_kn = (reservoir_pressure_kpa * 1000.0) * A_plunger / 1000.0   # [kN]

    A_rod = np.pi / 4.0 * rod_diameter_m**2
    rho_steel = 7850.0
    buoyancy = 1.0 - rho_fluid / rho_steel
    W_rod_kn = A_rod * rho_steel * g * rod_length_m * buoyancy / 1000.0

    omega = 2.0 * np.pi * spm / 60.0
    M_rod = A_rod * rho_steel * rod_length_m
    F_accel_kn = M_rod * (stroke_length_m / 2.0) * omega**2 / 1000.0

    peak_load_kn = float(W_rod_kn + F_fluid_kn + F_accel_kn)
    min_load_kn = float(max(W_rod_kn - F_accel_kn, 0.1))

    # 5. Pump fillage — function of reservoir pressure and viscosity
    #    Fillage drops when viscosity is very high (poor inflow to pump barrel)
    #    Fillage = 1.0 at low viscosity; degrades above ~500 cP
    fillage = float(np.clip(1.0 - 0.0003 * max(mu - 100.0, 0.0), 0.3, 1.0))

    # 6. Pump efficiency
    q_theoretical = (np.pi / 4.0) * plunger_dia_m**2 * stroke_length_m * spm * 1440.0
    pump_efficiency = float(np.clip(q_oil / max(q_theoretical, 1e-6), 0.05, 0.95))

    # 7. Motor power and energy
    P_kw = (peak_load_kn * stroke_length_m * spm) / (60.0 * motor_efficiency)
    q_bbl = max(q_oil * 6.2898, 0.001)
    kwh_bbl = float(P_kw * 24.0 / q_bbl)

    # 8. Rod float risk
    rf_ratio = rod_float_risk_ratio(
        stroke_length_m, spm, rod_diameter_m, rod_length_m, mu
    )
    rf_score = rod_float_risk_score_0_100(rf_ratio)

    # 9. SOR
    sor_val = float(steam_volume_cwe_m3 / max(cum_oil_m3, 0.1))

    return SurrogateResult(
        reservoir_temp_c=float(T_res),
        oil_viscosity_cp=float(mu),
        oil_rate_m3d=float(q_oil),
        pump_fillage_fraction=float(fillage),
        pump_efficiency_fraction=float(pump_efficiency),
        motor_power_kw=float(P_kw),
        kwh_per_bbl=float(kwh_bbl),
        peak_load_kn=float(peak_load_kn),
        min_load_kn=float(min_load_kn),
        rod_float_risk=float(rf_ratio),
        rod_float_risk_score=float(rf_score),
        sor=float(sor_val),
    )


def evaluate_batch(
    params_list: list[dict],
) -> list[SurrogateResult]:
    """
    Evaluate the surrogate for a batch of parameter dicts.
    Each dict must contain all keys expected by evaluate().
    """
    return [evaluate(**p) for p in params_list]


def surrogate_accuracy_report(n_samples: int = 200, seed: int = 42) -> dict:
    """
    Generate a report comparing surrogate vs full simulator on n_samples.
    Used in test_surrogate.py and the /health endpoint.

    Returns dict with R² for each key output.
    Minimum acceptable R² per output:
      oil_rate_m3d     0.97
      pump_efficiency  0.95
      kwh_per_bbl      0.95
      rod_float_risk   0.98
    """
    from ..well_system import WellSystem
    from ..config import WellParameters

    rng = np.random.default_rng(seed)
    results_surrogate = []
    results_full = []

    for _ in range(n_samples):
        spm = float(rng.uniform(2.0, 10.0))
        stroke = float(rng.uniform(1.0, 4.0))
        steam_vol = float(rng.uniform(200.0, 800.0))
        t_prod = float(rng.uniform(0.0, 60.0))

        params = WellParameters(spm=spm, stroke_length_m=stroke,
                                 steam_volume_cwe_m3=steam_vol)
        ws = WellSystem(params)
        ws.start_cycle()
        ws.advance_to_production()
        ws._t_production_days = t_prod
        full_state = ws.tick()

        surr = evaluate(
            steam_volume_cwe_m3=steam_vol,
            steam_quality=params.steam_quality,
            t_production_days=t_prod,
            cycle_number=ws.cycle_number,
            T_initial_c=params.initial_temp_c,
            T_steam_c=200.0,
            pay_thickness_m=params.pay_thickness_m,
            porosity=params.porosity,
            reservoir_pressure_kpa=full_state.reservoir_pressure_kpa,
            spm=spm,
            stroke_length_m=stroke,
            rod_length_m=params.rod_string_length_m,
            rod_diameter_m=params.rod_diameter_m,
            plunger_dia_m=params.pump_plunger_dia_m,
            api=params.api_gravity,
            cum_oil_m3=max(getattr(full_state, "cum_oil_m3", 1.0), 0.1),
        )
        results_surrogate.append(surr)
        results_full.append(full_state)

    def _r2(y_true: list, y_pred: list) -> float:
        yt = np.array(y_true, dtype=float)
        yp = np.array(y_pred, dtype=float)
        ss_res = np.sum((yt - yp)**2)
        ss_tot = np.sum((yt - yt.mean())**2)
        return float(1.0 - ss_res / max(ss_tot, 1e-9))

    # WellStateSnapshot field names used in the surrogate R² comparison.
    # full_state is a WellStateSnapshot dataclass (not a dict); use getattr.
    # Surrogate uses rod_float_risk; snapshot uses rod_float_risk_ratio.
    key_map = {
        "oil_rate_m3d": "oil_rate_m3d",
        "pump_efficiency_fraction": "pump_efficiency_fraction",
        "kwh_per_bbl": "kwh_per_bbl",
        "rod_float_risk": "rod_float_risk_ratio",
    }
    report = {}
    for surr_key, snap_key in key_map.items():
        full_vals = [getattr(s, snap_key, getattr(r, surr_key, 0.0))
                     for s, r in zip(results_full, results_surrogate)]
        surr_vals = [getattr(r, surr_key) for r in results_surrogate]
        report[surr_key] = _r2(full_vals, surr_vals)

    return report
