#!/usr/bin/env python3
"""
data/generate.py
Master synthetic dataset generation script.

Usage:
    python data/generate.py                # generate all datasets (default: 10 wells, 8 cycles)
    python data/generate.py --wells 5      # fewer wells (faster)
    python data/generate.py --cards 2000   # fewer dyno cards

Outputs to data/synthetic/:
    well_completion.parquet
    css_cycle_records.parquet
    production_history.parquet
    srp_operating_data.parquet
    dyno_cards_labeled.parquet
    rod_failure_history.parquet
    quality_report.json
    data_manifest.csv

All datasets are SYNTHETIC_HISTORICAL — generated by the physics simulator.
Calibrated to published petroleum engineering literature.
NOT validated on real Baghewala field operations.
"""

import sys
import os
import json
import time
import argparse
from pathlib import Path

# Ensure simulator is importable
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

import pandas as pd
import numpy as np

OUTPUT_DIR = ROOT / "data" / "synthetic"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def log(msg: str) -> None:
    print(f"[generate] {msg}", flush=True)


def save(df: pd.DataFrame, name: str) -> Path:
    """Save DataFrame to parquet and return path."""
    p = OUTPUT_DIR / f"{name}.parquet"
    df.to_parquet(p, index=False)
    log(f"  Saved {name}.parquet  ({len(df):,} rows, {len(df.columns)} cols)")
    return p


def main(
    n_wells: int = 10,
    n_cycles: int = 8,
    n_cards: int = 8000,
    seed: int = 42,
    start_date: str = "2019-01-01",
) -> None:
    t0 = time.time()
    log("=" * 60)
    log("YUKTI — Synthetic Dataset Generator")
    log("=" * 60)
    log(f"Wells: {n_wells} | Cycles: {n_cycles} | Dyno cards: {n_cards} | Seed: {seed}")
    log("")

    # ── 1. Well Completion ────────────────────────────────────────────────
    log("1/6  Well completion data...")
    from data.generators.well_completion import generate_well_completion
    df_wc = generate_well_completion(n_wells, seed)
    save(df_wc, "well_completion")

    # ── 2. CSS Cycle Records ──────────────────────────────────────────────
    log("2/6  CSS cycle records...")
    from data.generators.css_cycles import generate_css_cycles
    df_css = generate_css_cycles(n_wells, n_cycles, seed, start_date)
    save(df_css, "css_cycle_records")

    # ── 3. Production History ─────────────────────────────────────────────
    log("3/6  Production history (daily, all wells × all cycles)...")
    from data.generators.production_history import generate_production_history
    df_prod = generate_production_history(n_wells, n_cycles, seed, start_date)
    save(df_prod, "production_history")

    # ── 4. SRP Operating Data ─────────────────────────────────────────────
    log("4/6  SRP operating data (daily, with wave equation)...")
    from data.generators.srp_operating import generate_srp_operating
    df_srp = generate_srp_operating(n_wells, n_cycles, seed, start_date=start_date)
    save(df_srp, "srp_operating_data")

    # ── 5. Dynamometer Cards ──────────────────────────────────────────────
    log(f"5/6  Labeled dynamometer cards ({n_cards:,} cards)...")
    from data.generators.dyno_cards import generate_dyno_cards, FAULT_DISTRIBUTION
    df_dyno = generate_dyno_cards(n_wells, n_cards, seed)
    save(df_dyno, "dyno_cards_labeled")

    # ── 6. Rod Failure History ────────────────────────────────────────────
    log("6/6  Rod failure history...")
    from data.generators.rod_failures import generate_rod_failures
    df_fail = generate_rod_failures(n_wells, n_cycles, seed, start_date)
    save(df_fail, "rod_failure_history")

    # ── Quality Report ────────────────────────────────────────────────────
    log("")
    log("Generating data quality report...")
    from data.generators.quality_report import generate_quality_report
    report = generate_quality_report(OUTPUT_DIR)
    qr_path = OUTPUT_DIR / "quality_report.json"
    with open(qr_path, "w") as f:
        json.dump(report, f, indent=2)
    log(f"  Quality report: {qr_path}")

    # ── Data Manifest CSV ─────────────────────────────────────────────────
    manifest_rows = []
    for dataset_name, info in report["datasets"].items():
        manifest_rows.append({
            "dataset": dataset_name,
            "rows": info.get("rows", 0),
            "status": info.get("status", "?"),
            "file": f"{dataset_name}.parquet",
            "provenance": "SYNTHETIC_HISTORICAL",
            "note": "Generated by physics simulator. NOT real Baghewala data.",
        })
    df_manifest = pd.DataFrame(manifest_rows)
    manifest_path = OUTPUT_DIR / "data_manifest.csv"
    df_manifest.to_csv(manifest_path, index=False)
    log(f"  Data manifest: {manifest_path}")

    elapsed = time.time() - t0
    log("")
    log("=" * 60)
    log(f"Done in {elapsed:.1f}s  |  Status: {report['overall_status']}")
    log(f"Total rows: {report['total_rows']:,}")
    log("=" * 60)
    log("")
    log("PROVENANCE REMINDER:")
    log("  All data is SYNTHETIC_HISTORICAL — physics-based simulator output.")
    log("  Calibrated to published petroleum engineering literature.")
    log("  NOT validated on real Baghewala field operations.")
    log("=" * 60)

    # Print quality summary
    log("")
    log("Dataset Quality Summary:")
    for ds, info in report["datasets"].items():
        rows = info.get("rows", 0)
        status = info.get("status", "?")
        icon = "[OK]" if status == "OK" else "[!!]"
        log(f"  {icon} {ds:<35} {rows:>8,} rows  [{status}]")

    if report["overall_status"] != "OK":
        log("")
        log("WARNINGS detected — see quality_report.json for details.")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Baghewala synthetic datasets")
    parser.add_argument("--wells", type=int, default=10, help="Number of wells")
    parser.add_argument("--cycles", type=int, default=8, help="CSS cycles per well")
    parser.add_argument("--cards", type=int, default=8000, help="Number of dyno cards")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--start-date", type=str, default="2019-01-01")
    args = parser.parse_args()

    main(
        n_wells=args.wells,
        n_cycles=args.cycles,
        n_cards=args.cards,
        seed=args.seed,
        start_date=args.start_date,
    )
